
version: 2

sources:
    - name: raw
      schema: gz_raw_data
      description: greenwez raw data source 
      tables:

          - name: sales
            identifier: raw_gz_sales
            description: sales of greewneez / we have one row per product_id found in each order_id 
            columns: 
              - name: "(orders_id || '-' || pdt_id)"
                description: primary key of the table
                tests:
                  - unique 
                  - not_null 

          - name: product
            identifier: raw_gz_product
            description: purchase_price by products_id
            columns:
              - name: products_id
                description: primary key of the table
                tests:
                  - unique 
                  - not_null 
                      
                                  
          - name: ship
            identifier: raw_gz_ship
            description: shipping_fees by order_id 
            columns:
              - name: orders_id
                description: primary key of the table
                tests:
                  - unique 
                  - not_null 

          - name: adwords
            identifier: raw_gz_adwords
            columns:
              - name: "(date_date || '-' || paid_source || '-' || campaign_key )"
                description: primary key of the table
                tests:
                  - unique 
                  - not_null 

          - name: bing
            identifier: raw_gz_bing
            columns:
              - name: "(date_date || '-' || paid_source || '-' || campaign_key )"
                description: primary key of the table
                tests:
                  - unique 
                  - not_null
          - name: criteo
            identifier: raw_gz_criteo
            columns:
              - name: "(date_date || '-' || paid_source || '-' || campaign_key )"
                description: primary key of the table
                tests:
                  - unique 
                  - not_null

          - name: facebook
            identifier: raw_gz_facebook
            columns:
              - name: "(date_date || '-' || paid_source || '-' || campaign_key )"
                description: primary key of the table
                tests:
                  - unique 
                  - not_null
          
models:
              - name: int_campaigns_day
                description: performance of the marketing campaign per day
                columns:                             
                  - name: ads_cost 
                    description : cost aquisition per day 
                  - name: ads_impression 
                    description: nb of impression of the campaign per day
                  - name : ads_clicks 
                    description: nb of click of the campaign per day
                  - name: date_date
                    tests:
                      - not_null  


              - name : finance_camapigns_day
                description : report of revenu by campaign
                columns: 
                  - name : ads_margin 
                    description : margin per ampaign per day
                                    
                           