
version: 2

sources:
    - name: raw
      schema: gz_raw_data
      description: greenwez raw data source 
      tables:

          - name: sales
            identifier: raw_gz_sales
            description: sales of greewneez / we have one row per product_id found in each order_id 

          - name: product
            identifier: raw_gz_product
            description: purchase_price by product_id

          - name: ship
            identifier: raw_gz_ship
            description: shipping_fees by order_id 